### ISSUE TITLE
Projekt in Monatzstab einfügen

### ISSUE THREAD

**Issue by agrafikr** [polygontwist/PROSTd-App#5]
geht auch ein Projekt mehrmals pro Tag einzufügen?

**Comment by polygontwist** [comment]
Aufgrund der IDs (2017_01_22-Projektname) der Einträge nicht möglich. Ein Stundendatensatz sieht so z.B. aus:
`{"dat":"2016-12-24",
"kommentar":"Varianten",
"stunden":0.5,
"typ":"R",
"user":"andreas"}`
Dabei ist "dat" = die ID des Eintrages.
Die Idee ist pro Tag ein Prokjektitem zu haben. Hat man aber z.B. einen Kunden mit mehreren Projekten ist für jedes Projekt ein "Projekt" anzulegen.
