### ISSUE TITLE
BUG: nach Installation v0.1.29 keine Daten sichtbar

### ISSUE THREAD

**Issue by agrafikr** [polygontwist/PROSTd-App#60]
bei "mein Tag"

**Comment by agrafikr** [comment]
fix: in optionen.txt (Pfad ist unter Einstellungen "Deine Datenliegen in" zu finden) folgende Werte hinzufügen:

`,"urlabstageprojahrabjahr":2019,"wochenarbeitstage":[true,true,true,true,true,false,false]`

wird in Version v0.1.30 gefixt werden.

**Comment by polygontwist** [comment]
fixed in v0.1.30
