### ISSUE TITLE
Fensterposition bei Mehrmonitorsetup

### ISSUE THREAD

**Issue by agrafikr** [polygontwist/PROSTd-App#70]
Fenster kann in unsichtbaren Bereich verschwinden, bei Mehrmonitorbetrieb und wechselnende Hauptfensterposition.

Momentante Hilfe: Datei "optionen.txt" unter Documents\PROSTd\userData 
-löschen: man muss aber die Einstellungen checken (Urlaubstage, Arbeitszeit)
-editieren: x und y bei windowsize auf 0, oder 
-den Tag + Eigenschaften "windowsize" löschen (auf Syntax achten!)

**Comment by polygontwist** [comment]
fixed v1.41
